#!/usr/bin/env bash
cd "$(dirname "$0")/.."
[ $PORT ]     || PORT=3000
[ $RACK_ENV ] || RACK_ENV=development

cmd="bundle exec rackup -s puma -p $PORT"
[[ $RACK_ENV == "development" ]] && exec rerun "$cmd"
exec $cmd
